name: Publish Docker image

on:
  push:
    branches:
      - main
      # For testing the changes to the workflow to tag the commit and allow workflow dispatch. 
      # We can get rid of this once we are happy with the updated workflow
      - jlewi/oidc
  # Allow manual triggering
  # This allows building images from branches
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:commit-${{ format('{0}', github.sha | slice(0, 7)) }}
